version: '2'
services:
  kafkabroker:
    retain_ip: true
    scale: 3
    start_on_create: true
  zookeeper:
    retain_ip: true
    scale: 3
    start_on_create: true
  kafkabroker-volume:
    retain_ip: true
    scale: 3
    start_on_create: true
  zookeeper-conf:
    retain_ip: true
    scale: 3
    start_on_create: true
  zookeeper-volume:
    retain_ip: true
    scale: 3
    start_on_create: true
  kafkabroker-conf:
    retain_ip: true
    scale: 3
    start_on_create: true
